### ISSUE TITLE
JSONDecodeError

### ISSUE THREAD

**Issue by luisarbmol** [Guilhem23/Jackett_Indexerr#10]
Hello to all! First of all thank you very much for the work you are doing with this script, it makes life much easier!

After a while I'm having problems with it, I'm having problems running it. I'm going to try to reproduce here what I'm doing exactly so you can have a better idea and if you could help me. 

I have cloned the repository locally, executed the **_make run_** without problems, configured the **_config.ini_** with my values after launching the program for the first time, which I put here (I have modified the api keys, for privacy):

```[default]
jackett_apikey = myapikey
jackett_url = http://localhost:9117
indexer_prefix = AUTO:
[sonarr]
apikey = myapikey
url = http://localhost:8989/api
categoryprefixes = ['TV']
animecategoryprefixes = ['Anime', 'TV']
[radarr]
apikey = myapikey
url = http://localhost:7878/api
categoryprefixes = ['Movies']
animecategoryprefixes = ['Anime', 'Movies']
[lidarr]
apikey = myapikey
url = http://localhost:8686/api
categoryprefixes = ['Audio']
```

And I'm finding this problem, I don't know how to debug here and I can't make it work:

```[root@server Jackett_Indexerr]# make run
# add you run commands here
pipenv run python add_indexer.py
135 indexers availlable in Jackett
Traceback (most recent call last):
  File "add_indexer.py", line 164, in <module>
    add_indexers(app)
  File "add_indexer.py", line 58, in add_indexers
    app_schemas = get_jsomparsed_data(config[app]['url'] + app_schema_url + "?apikey="+config[app]['apikey'])
  File "add_indexer.py", line 45, in get_jsomparsed_data
    return json.loads(data)
  File "/usr/lib64/python3.6/json/__init__.py", line 354, in loads
    return _default_decoder.decode(s)
  File "/usr/lib64/python3.6/json/decoder.py", line 339, in decode
    obj, end = self.raw_decode(s, idx=_w(s, 0).end())
  File "/usr/lib64/python3.6/json/decoder.py", line 357, in raw_decode
    raise JSONDecodeError("Expecting value", s, err.value) from None
json.decoder.JSONDecodeError: Expecting value: line 1 column 1 (char 0)
make: *** [Makefile:162: run] Error 1
```

Thank you very much also for everything! Thanks for the script!

**Comment by luisarbmol** [comment]
Fuck! I solved this!

All the problem was I forgot to put the **/** at the end od the apps URL. 

Works if I put these like this:

```
jackett_apikey = myapikey
jackett_url = http://localhost:9117
indexer_prefix = AUTO:
[sonarr]
apikey = myapikey
url = http://localhost:8989/api/
categoryprefixes = ['TV']
animecategoryprefixes = ['Anime', 'TV']
[radarr]
apikey = myapikey
url = http://localhost:7878/api/
categoryprefixes = ['Movies']
animecategoryprefixes = ['Anime', 'Movies']
[lidarr]
apikey = myapikey
url = http://localhost:8686/api/
categoryprefixes = ['Audio']
```
