### ISSUE TITLE
No connection could be made because the target machine actively refused it

### ISSUE THREAD

**Issue by pixelpox** [Guilhem23/Jackett_Indexerr#12]
Hi,

I tried to run your script on windows 10 and got the below error message.

my set-up is that the Jackett/Sonarr/Radarr are on a different machine (actually they are running inside docker containers using the linuxserver.io image). I am then running the script on my windows client.

my install steps were to clone the repo.
run pip install -r requirements.txt
then use the add_indexer.py to create the dummy file,

Ill try and run the script on a linux machine, I didn't see anyone else with this issue so thought it would be best to feedback my issue incase someone else runs into it.

I tried both HTTP and HTTPS in the URLs but no dice.

However, thank you very much for publishing your script :)

```
[default]
jackett_apikey = APIKEY1
jackett_url = https://192.168.1.12/jackett
indexer_prefix = AUTO: 

[sonarr]
apikey = APIKEY2
url = https://192.168.1.12/sonarr/api/
categoryprefixes = ['TV']
animecategoryprefixes = ['Anime', 'TV']

[radarr]
apikey = APIKEY3
url = https://192.168.1.12/radarr/api/
categoryprefixes = ['Movies']
animecategoryprefi
```

```PS C:\Users\simon\Jackett_Indexerr> python .\add_indexer.py
Traceback (most recent call last):
  File "C:\Users\simon\AppData\Local\Programs\Python\Python38-32\lib\urllib\request.py", line 1319, in do_open
    h.request(req.get_method(), req.selector, req.data, headers,
  File "C:\Users\simon\AppData\Local\Programs\Python\Python38-32\lib\http\client.py", line 1230, in request
    self._send_request(method, url, body, headers, encode_chunked)
  File "C:\Users\simon\AppData\Local\Programs\Python\Python38-32\lib\http\client.py", line 1276, in _send_request
    self.endheaders(body, encode_chunked=encode_chunked)
  File "C:\Users\simon\AppData\Local\Programs\Python\Python38-32\lib\http\client.py", line 1225, in endheaders
    self._send_output(message_body, encode_chunked=encode_chunked)
  File "C:\Users\simon\AppData\Local\Programs\Python\Python38-32\lib\http\client.py", line 1004, in _send_output
    self.send(msg)
  File "C:\Users\simon\AppData\Local\Programs\Python\Python38-32\lib\http\client.py", line 944, in send
    self.connect()
  File "C:\Users\simon\AppData\Local\Programs\Python\Python38-32\lib\http\client.py", line 915, in connect
    self.sock = self._create_connection(
  File "C:\Users\simon\AppData\Local\Programs\Python\Python38-32\lib\socket.py", line 808, in create_connection
    raise err
  File "C:\Users\simon\AppData\Local\Programs\Python\Python38-32\lib\socket.py", line 796, in create_connection
    sock.connect(sa)
ConnectionRefusedError: [WinError 10061] No connection could be made because the target machine actively refused it

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File ".\add_indexer.py", line 52, in <module>
    all_indexers = get_jsomparsed_data_from_xml(jackett_indexers_url)
  File ".\add_indexer.py", line 37, in get_jsomparsed_data_from_xml
    response = request.urlopen(url)
  File "C:\Users\simon\AppData\Local\Programs\Python\Python38-32\lib\urllib\request.py", line 222, in urlopen
    return opener.open(url, data, timeout)
  File "C:\Users\simon\AppData\Local\Programs\Python\Python38-32\lib\urllib\request.py", line 525, in open
    response = self._open(req, data)
  File "C:\Users\simon\AppData\Local\Programs\Python\Python38-32\lib\urllib\request.py", line 542, in _open
    result = self._call_chain(self.handle_open, protocol, protocol +
  File "C:\Users\simon\AppData\Local\Programs\Python\Python38-32\lib\urllib\request.py", line 502, in _call_chain
    result = func(*args)
  File "C:\Users\simon\AppData\Local\Programs\Python\Python38-32\lib\urllib\request.py", line 1348, in http_open
    return self.do_open(http.client.HTTPConnection, req)
  File "C:\Users\simon\AppData\Local\Programs\Python\Python38-32\lib\urllib\request.py", line 1322, in do_open
    raise URLError(err)
urllib.error.URLError: <urlopen error [WinError 10061] No connection could be made because the target machine actively refused it>
PS C:\Users\simon\Jackett_Indexerr>

```

**Comment by pixelpox** [comment]
Sorry,

I'm a complete spanner, it just dawned on me that the URLs didn't have the port numbers on them.

If anyone is interested my config.ini now looks like this and it's working.

```
[default]
jackett_apikey = APIKEY1
jackett_url = http://192.168.1.12:9117/jackett
indexer_prefix = AUTO: 

[sonarr]
apikey = APIKEY2
url = http://192.168.1.12:8989/sonarr/api/
categoryprefixes = ['TV']
animecategoryprefixes = ['Anime', 'TV']

[radarr]
apikey = APIKEY3
url = http://192.168.1.12:7878/radarr/api/
categoryprefixes = ['Movies']
animecategoryprefixes = ['Anime', 'Movies']
```
